# Generated by Django 5.1.5 on 2025-08-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_boncommande_ligneboncommande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='montant_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
