# Generated by Django 5.1.5 on 2025-08-22 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_vente_montant_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignecommande',
            name='est_validee',
            field=models.BooleanField(default=False),
        ),
    ]
