# Generated by Django 5.1.5 on 2025-08-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_lignecommande_est_validee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lignecommande',
            name='est_validee',
        ),
        migrations.AddField(
            model_name='commande',
            name='est_validee',
            field=models.BooleanField(default=False),
        ),
    ]
