# Generated by Django 5.1.5 on 2025-08-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_lignecommande_est_validee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bordereaulivraison',
            name='numero_bordereau',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
