# Generated by Django 5.1.5 on 2025-08-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_bordereaulivraison_numero_bordereau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bordereaulivraison',
            name='numero_bordereau',
        ),
    ]
